spring.application.name=pharmacy-backend
# Cổng chạy ứng dụng
server.port=8080

spring.datasource.url=jdbc:sqlserver://DESKTOP-CRU5KCB:1433;databaseName=PharmacyDB;encrypt=false;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect